image:
    - Visual Studio 2015
    - Visual Studio 2017
environment:
    PATH: C:\Python36-x64;C:\Python36-x64\Scripts;$(PATH)
cache:
    - C:\ProgramData\chocolatey\bin -> .appveyor.yml
    - C:\ProgramData\chocolatey\lib -> .appveyor.yml
    - c:\tools\vcpkg\installed\
clone_folder: C:\khiva
platform:
    - x64
before_build:
  - appveyor DownloadFile "http://registrationcenter-download.intel.com/akdlm/irc_nas/12512/opencl_runtime_16.1.2_x64_setup.msi"
  - start /wait msiexec /i opencl_runtime_16.1.2_x64_setup.msi /qn /l*v msiexec1.log
  - appveyor DownloadFile "https://drive.google.com/uc?authuser=0&id=1uM_QI1nrQS0MCvOt3DR96NiZQMP7n6DE&export=download" -FileName ArrayFire-no-gl-d920eae2.exe
  - start /wait ArrayFire-no-gl-d920eae2.exe /S
  - start /wait choco install doxygen.install
  - start /wait choco install graphviz
  - start /wait pip3.exe install sphinx sphinx_rtd_theme breathe cpp-coveralls
  - vcpkg install --triplet x64-windows boost-math gtest benchmark eigen3
  - mkdir build && cd build
for:
-
  matrix:
    only:
      - image: Visual Studio 2015
  build_script:
  - cmake .. -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DKHIVA_USE_CONAN=OFF -G"Visual Studio 14 Win64"
  - cmake --build . --config Release
  matrix:
    only:
      - image: Visual Studio 2017
  build_script:
  - cmake .. -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DKHIVA_USE_CONAN=OFF -G"Visual Studio 15 Win64"
  - cmake --build . --config Release
test_script:
    - ctest -C Release --output-on-failure