image:
    - Visual Studio 2015
environment:
    PATH: C:\Python36-x64;C:\Python36-x64\Scripts;$(PATH)
clone_folder: C:\khiva
platform:
    - x64
before_build:
  - appveyor DownloadFile "http://registrationcenter-download.intel.com/akdlm/irc_nas/12512/opencl_runtime_16.1.2_x64_setup.msi"
  - start /wait msiexec /i opencl_runtime_16.1.2_x64_setup.msi /qn /l*v msiexec1.log
  - appveyor DownloadFile "http://arrayfire.s3.amazonaws.com/3.5.1/ArrayFire-v3.5.1.exe"
  - start ArrayFire-v3.5.1.exe /S
  - start /wait .CI/appveyor/lookAF.bat
  - choco install doxygen.install
  - choco install graphviz
  - start /wait pip3.exe install conan sphinx sphinx_rtd_theme breathe cpp-coveralls
  - start /wait conan remote add -f conan-mpusz https://api.bintray.com/conan/mpusz/conan-mpusz
  - start /wait conan remote add -f boost_math https://api.bintray.com/conan/bincrafters/public-conan
build_script:
    - mkdir build && cd build
    - cmake .. -G"Visual Studio 14 Win64"
    - cmake --build . --config Release
test_script:
    - ctest -C Release --output-on-failure