language: cpp
sudo: required
dist: trusty


install:
  - source .CI/travis/install-intel.sh
  - source .CI/travis/install-arrayfire.sh
  - source .CI/travis/install-cmake.sh
  - source .CI/travis/install_linux.sh

script:
  - source .CI/travis/build.sh

after_success:
  - source .CI/travis/codecov.sh