language: cpp
sudo: required
dist: trusty

compiler:
  - g++
  - clang

cache:
    directories:
      - ${HOME}/.conan

install:
  - source .CI/travis/install-intel.sh
  - source .CI/travis/install-arrayfire.sh
  - source .CI/travis/install-cmake.sh
  - source .CI/travis/install_linux.sh

script:
  - source .CI/travis/build.sh
