
os: linux
dist: trusty
sudo: required

env:
  global:
    - ARRAYFIRE=/opt/arrayfire

language: cpp
compiler: g++

addons:
  apt:
    packages:
    - lcov
    - python3 
    - python3-pip
    - libboost-all-dev
    - doxygen 
    - graphviz

cache:
    directories:
      - ${HOME}/.conan

before_install:
  - source .CI/travis/install-intel.sh 2>&1 > /dev/null
  - source .CI/travis/install-arrayfire.sh 2>&1 > /dev/null
  - source .CI/travis/install-cmake.sh 2>&1 > /dev/null

install:
  - source .CI/travis/install.sh 2>&1 > /dev/null

script:
  - source .CI/travis/build.sh 2>&1 > /dev/null

after_success:
  - source .CI/travis/codecov.sh