
language: cpp
sudo: required

env:
  global:
    - ARRAYFIRE=/opt/arrayfire

matrix:
  include:
    # works on Trusty
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - lcov
            - python3 
            - python3-pip
            - libboost-all-dev
            - doxygen 
            - graphviz
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    # works on Trusty
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - lcov
            - python3 
            - python3-pip
            - libboost-all-dev
            - doxygen 
            - graphviz
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
    
    # works on Mac Os
    - os: osx
      osx_image: xcode9.3
      env:
        - MATRIX_EVAL="sudo brew install gcc5 lcov python doxygen graphviz && CC=gcc-5 && CXX=g++-5"

    # works on Mac Os
    - os: osx
      osx_image: xcode9.3
      env:
        - MATRIX_EVAL="sudo brew install lcov python doxygen graphviz"
  
cache:
    directories:
      - ${HOME}/.conan

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - source .CI/travis/install-intel.sh 2>&1 > /dev/null
  - source .CI/travis/install-arrayfire.sh 2>&1 > /dev/null
  - source .CI/travis/install-cmake.sh 2>&1 > /dev/null
  - source .CI/travis/install.sh 2>&1 > /dev/null

script:
  - source .CI/travis/build.sh

after_success:
  - source .CI/travis/codecov.sh

