
os: linux
dist: trusty
sudo: required

env:
  global:
    - ARRAYFIRE=/opt/arrayfire

language: cpp
compiler: g++

addons:
  apt:
    packages:
    - lcov
    - kcov

cache:
    directories:
      - ${HOME}/.conan

before_install:
  - source .CI/travis/install-intel.sh
  - source .CI/travis/install-arrayfire.sh
  - source .CI/travis/install-cmake.sh

install:
  - source .CI/travis/install.sh

script:
  - source .CI/travis/build_and_test.sh

after_success:
  - cd ${HOME}/build
  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*" -E ".*bindings/.*" -E ".*benchmarks/.*" -E ".*cmake/.*" -E "/usr/*.*" -E "/opt/*.*" -E "/home/travis/.conan/*.*" 