
os: linux
dist: trusty
sudo: required

language: cpp
compiler: g++

before_install:
  - source .CI/travis/install-intel.sh
  - source .CI/travis/install-arrayfire.sh
  - source .CI/travis/install-cmake.sh

install:
  - source .CI/travis/install.sh

script:
    - mkdir -p build && cd build
    - ../bin/cmake ..
    - make -j4
