


os: linux
dist: trusty
sudo: required

language: cpp
compiler:
- clang

before_install:
  - sudo apt-get update
  - sudo apt-get install -y python3 libboost-all-dev libeigen3-dev
  - source ./.ci/travis/install-intel.sh
  - source ./.ci/travis/install-arrayfire.sh

install:
  - source ./.ci/travis/install.sh
  - mkdir build
  - cd build
  - cmake ..
  - make install