
sudo: required
dist: trusty
compiler:
- clang
os:
- linux

# It is not really needed, other than for showing correct language tag in Travis CI build log.
language: cpp

before_install:
  - source .CI/travis/install.sh

install:
  - source .CI/travis/run.sh

