sudo: required

services:
  - docker

# It is not really needed, other than for showing correct language tag in Travis CI build log.
language: cpp

before_install:
  - source .CI/travis/install.sh 2>&1 > /dev/null

install:
  - source .CI/travis/run.sh

