
language: cpp
sudo: required

env:
  global:
    - ARRAYFIRE=/opt/arrayfire

cache:
  directories:
    - ${HOME}/.conan

os: linux
  dist: trusty
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        update: true
        packages:
          - lcov
          - python3 
          - python3-pip
          - libboost-all-dev
          - doxygen 
          - graphviz

install:
  - source .CI/travis/install-intel.sh 
  - source .CI/travis/install-arrayfire.sh 
  - source .CI/travis/install-cmake.sh 
  - source .CI/travis/install.sh
  
script:
  - source .CI/travis/build.sh

after_success:
  - source .CI/travis/codecov.sh

