
os: linux
dist: trusty
sudo: required

env:
  global:
    - ARRAYFIRE=/opt/arrayfire

language: cpp
compiler: g++

addons:
  apt:
    packages:
    - lcov

cache:
    directories:
        - ${HOME}/.conan

before_install:
  - source .CI/travis/install-intel.sh
  - source .CI/travis/install-arrayfire.sh
  - source .CI/travis/install-cmake.sh

install:
  - source .CI/travis/install.sh

script:
  - source .CI/travis/build_and_test.sh

after_success:
  - cd build
  - lcov --directory test --base-directory . --capture --output-file coverage.info
  - lcov --remove coverage.info '/usr*' '/opt*' '*/cl.hpp' -o coverage.info
  - bash <(curl -s https://codecov.io/bash)

